### PR TITLE
add pkgdown site

### PR DESCRIPTION
**Pull request by katherinesimeon**
This is the actual PR. Sorry!

### CODE REVIEW

**Comment by katherinesimeon** [comment]
Current link to site here: https://katherinesimeon.github.io/updraft/

**Review by jameslamb — CHANGES_REQUESTED** [review]
This looks great! Thanks for doing it and for including the link to how it rendered on your personal fork...made it a lot easier to review.

Please just fix the conflicts in Rbuildignore and gitignore and push another commit to this branch, then we'll merge it up!

**Comment by katherinesimeon** [comment]
Let me know what else you need!

**Comment by jameslamb** [comment]
@cwschultz88 can we merge this?

**Review by jameslamb — APPROVED** [review]

**Comment by cwschultz88** [comment]
Sorry @katherinesimeon , this should have not taken this long to close out!!! Everything looks great. Thanks so much!

**Pull request merged**
